# File: azure-pipelines.yml
trigger:
  - master

schedules:
- cron: "0 13 * * *"
  displayName: Daily load test run
  branches:
    include:
    - master

parameters:
- name: env
  displayName: Environment
  type: string
  default:
  values:
  - https://www.saucedemo.com
  - https://www.saucedemo.test.com
- name: users
  displayName: Number of concurrent users
  type: number
  default: 1
  values:
    - 1
    - 2
    - 3
    - 4
    - 5

pool:
  name: Default
  demands:
   - agent.name -equals Ians-Windows-Laptop
jobs:
  - job: RunJmeterTests
    displayName: 'Run Jmeter Tests'
    timeoutInMinutes: 120
    steps:
      - powershell: | 
          (Get-Content $(System.DefaultWorkingDirectory)/test/jmeter_selenium_tests.jmx) -Replace 'ThreadGroup.num_threads">1<', 'ThreadGroup.num_threads">${{parameters.users}}<' | Set-Content $(System.DefaultWorkingDirectory)/test/jmeter_selenium_tests.jmx
        displayName: 'Replace number of concurrent users'

      - powershell: |
          (Get-Content $(System.DefaultWorkingDirectory)/test/jmeter_selenium_tests.jmx) -Replace 'http://localhost:3000', '{{parameters.env}}' | Set-Content $(System.DefaultWorkingDirectory)/test/jmeter_selenium_tests.jmx
        displayName: 'Replace number of concurrent users'

      - script: |
          C:\temp\apache-jmeter-5.5\bin\jmeter.bat -n -t $(System.DefaultWorkingDirectory)/test/jmeter_selenium_tests.jmx -l results/results.jtl -j results/output.log -e -o report
        displayName: 'Run Jmeter Tests'

      - script: |
          python $(System.DefaultWorkingDirectory)/src/jtl_junit_converter.py results/results.jtl results/output.xml
        displayName: 'Results: Convert Jmeter Results to Junit format'

      #- task: PublishTestResults@2
      #  inputs:
      #    testResultsFormat: 'JUnit'
      #   testResultsFiles: 'results/output.xml'
      #    failTaskOnFailedTests: false
      #  displayName: 'Results: Publish Load Test Results'

      - publish: $(System.DefaultWorkingDirectory)/results
        artifact: jmeter-results
        condition: always()
        displayName: 'Results: Publish Load Test Artifact'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: report
          artifact: jmeter-report
        displayName: 'Publish JMeter HTML Report'









